let settings,content,map,catalog=[];
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const sectionLabels={freshFish:"Fresh Fish — Beer Battered",crumbed:"Fresh Fish — Crumbed",grilled:"Fresh Fish — Grilled",addChips:"Add Chips",burgers:"Burgers",tacos:"Tacos",packs:"Packs",snacks:"Snacks",chips:"Chips"};
async function api(url,o={}){const r=await fetch(url,{headers:{"Content-Type":"application/json"},...o});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||r.statusText);return d}
async function begin(){const s=await api("/api/admin/session");if(!s.authenticated)return;$("#login").hidden=true;$("#app").hidden=false;[settings,content,map]=await Promise.all([api("/api/settings"),api("/api/admin/content"),api("/api/admin/map")]);fill();renderPromos();await loadCatalog();loadLiveStatus();loadPersistenceStatus();fitPreview();loadSystemHealth();}
$("#login-form").onsubmit=async e=>{e.preventDefault();try{await api("/api/admin/login",{method:"POST",body:JSON.stringify({password:$("#password").value})});begin()}catch(x){$("#login-error").textContent=x.message}};
$("#logout").onclick=async()=>{await api("/api/admin/logout",{method:"POST"});location.reload()};
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.hidden=true);$("#"+b.dataset.tab).hidden=false;if(b.dataset.tab==="backups")loadLocalBackups()});
function fill(){$("#location").value=settings.square.locationId;$("#adobe").value=settings.theme.adobeFontsUrl;$("#red").value=settings.theme.red;$("#navy").value=settings.theme.navy;$("#cream").value=settings.theme.cream;$("#aqua").value=settings.theme.aqua;$("#weekend").checked=settings.display.weekendSurchargeOnlyOnWeekends}
async function loadCatalog(force=false){try{const activeOnly=$("#active-only")?.checked!==false,p=new URLSearchParams({activeOnly:activeOnly?"1":"0"});if(force)p.set("refresh","1");catalog=await api("/api/admin/catalog?"+p);$("#square-state").textContent=`Connected — ${catalog.length} ${activeOnly?"active ":""}variations found`;$("#catalog-count").textContent=`${catalog.length} shown`;renderItems()}catch(e){$("#square-state").textContent=e.message}}
$("#refresh").onclick=()=>loadCatalog(true);$("#active-only").onchange=()=>loadCatalog(false);
function squareOptions(id=""){return `<option value="">Not linked / custom item</option>`+catalog.map(x=>`<option value="${esc(x.id)}" ${x.id===id?"selected":""}>${esc(x.itemName)} — ${esc(x.variationName||"Default")} — $${Number(x.price).toFixed(2)}</option>`).join("")}
function getOverride(id){return content.overrides[id]||(content.overrides[id]={})}
function rowCard(section,index,row){const o=getOverride(row.id);return `<div class="item" data-section="${section}" data-index="${index}" data-id="${esc(row.id)}"><div class="drag-controls"><button class="move-up" title="Move up">↑</button><button class="move-down" title="Move down">↓</button><span class="position">${index+1}</span></div><label class="square-field">Square variation<select class="sid">${squareOptions(row.squareVariationId)}</select></label><label>Display name<input class="name" value="${esc(o.name??row.name)}"></label><label>Detail<input class="detail-input" value="${esc(row.detail||"")}"></label><label>Origin<input class="origin-input" maxlength="2" value="${esc(row.origin||"")}"></label><label>Price text<input class="price-text" value="${esc(row.priceText||"")}" placeholder="Square price"></label><label>Move to<select class="move-section">${Object.entries(sectionLabels).map(([k,v])=>`<option value="${k}" ${k===section?"selected":""}>${esc(v)}</option>`).join("")}</select></label><label>Badge<input class="badge" value="${esc(o.badge||"")}"></label><label class="check"><input class="sold" type="checkbox" ${o.forceSoldOut?"checked":""}> Sold out</label><label class="check"><input class="hidden" type="checkbox" ${o.hidden?"checked":""}> Hidden</label><button class="delete danger">Delete</button></div>`}
function renderItems(){const host=$("#items-list");host.innerHTML=Object.entries(sectionLabels).map(([section,label])=>{const rows=map.sections[section]||[];return `<section class="builder-section" data-builder-section="${section}"><div class="section-head"><div><h2>${esc(label)}</h2><span>${rows.length} item${rows.length===1?"":"s"}</span></div><button class="add-row primary" data-section="${section}">+ Add item</button></div><div class="section-rows">${rows.map((r,i)=>rowCard(section,i,r)).join("")||'<p class="empty">No items in this section.</p>'}</div></section>`}).join("");bindBuilder();loadMappingAudit(false)}
function syncCard(el){const section=el.dataset.section,index=Number(el.dataset.index),row=map.sections[section][index],o=getOverride(row.id);row.squareVariationId=el.querySelector(".sid").value;delete row.squareVariationIds;row.name=el.querySelector(".name").value.trim()||"NEW ITEM";row.detail=el.querySelector(".detail-input").value.trim();row.origin=el.querySelector(".origin-input").value.trim().toUpperCase();row.priceText=el.querySelector(".price-text").value.trim();if(!row.priceText)delete row.priceText;o.name=row.name;o.badge=el.querySelector(".badge").value.trim();o.forceSoldOut=el.querySelector(".sold").checked;o.hidden=el.querySelector(".hidden").checked}
function syncAllCards(){document.querySelectorAll(".item").forEach(syncCard)}
function bindBuilder(){document.querySelectorAll(".add-row").forEach(b=>b.onclick=()=>openAdd(b.dataset.section));document.querySelectorAll(".item").forEach(el=>{el.querySelector(".move-up").onclick=()=>{moveRow(el,-1);queueMenuAutosave()};el.querySelector(".move-down").onclick=()=>{moveRow(el,1);queueMenuAutosave()};el.querySelector(".move-section").onchange=e=>{moveSection(el,e.target.value);queueMenuAutosave()};el.querySelector(".delete").onclick=()=>{deleteRow(el);queueMenuAutosave()};el.querySelectorAll("input,select").forEach(x=>x.addEventListener("change",queueMenuAutosave))})}
function moveRow(el,delta){syncAllCards();const s=el.dataset.section,i=Number(el.dataset.index),j=i+delta;if(j<0||j>=map.sections[s].length)return;[map.sections[s][i],map.sections[s][j]]=[map.sections[s][j],map.sections[s][i]];renderItems()}
function moveSection(el,target){syncAllCards();const s=el.dataset.section,i=Number(el.dataset.index);if(target===s)return;const [row]=map.sections[s].splice(i,1);map.sections[target].push(row);renderItems()}
function deleteRow(el){const s=el.dataset.section,i=Number(el.dataset.index),row=map.sections[s][i];if(!confirm(`Delete ${row.name} from the menu?`))return;map.sections[s].splice(i,1);delete content.overrides[row.id];renderItems()}
function openAdd(section){const d=$("#add-dialog");$("#add-section").innerHTML=Object.entries(sectionLabels).map(([k,v])=>`<option value="${k}" ${k===section?"selected":""}>${esc(v)}</option>`).join("");$("#add-square").innerHTML=squareOptions();$("#add-name").value="";$("#add-detail").value="";$("#add-origin").value="";$("#add-price").value="";$("#add-price-text").value="";d.showModal()}
$("#add-square").onchange=e=>{const x=catalog.find(v=>v.id===e.target.value);if(x){$("#add-name").value=x.itemName;$("#add-price").value=x.price||""}};
$("#add-form").onsubmit=e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const section=$("#add-section").value,sid=$("#add-square").value,cat=catalog.find(x=>x.id===sid),name=$("#add-name").value.trim();if(!name)return;const row={id:`custom-${crypto.randomUUID()}`,name,detail:$("#add-detail").value.trim(),origin:$("#add-origin").value.trim().toUpperCase(),squareVariationId:sid,autoSquareMatch:false};const priceText=$("#add-price-text").value.trim(),price=Number($("#add-price").value);if(priceText)row.priceText=priceText;else if(Number.isFinite(price)&&price>=0)row.price=price;else if(cat)row.price=Number(cat.price||0);map.sections[section].push(row);content.overrides[row.id]={};$("#add-dialog").close();renderItems();queueMenuAutosave()};
function renderPromos(){$("#promos-list").innerHTML=(content.promotions||[]).map((p,i)=>`<div class="promo-row" data-i="${i}"><label>Name<input class="pn" value="${esc(p.name)}"></label><label>Message<input class="pm" value="${esc(p.message)}"></label><label>Start<input class="ps" type="time" value="${esc(p.start)}"></label><label>End<input class="pe" type="time" value="${esc(p.end)}"></label><label><input class="pen" type="checkbox" ${p.enabled?"checked":""}> Enabled</label></div>`).join("")}
$("#add-promo").onclick=()=>{content.promotions.push({id:crypto.randomUUID(),name:"New promotion",message:"",enabled:false,days:[1,2,3,4,5],start:"11:30",end:"19:00"});renderPromos()};
let autoSaveTimer=null,autoSaving=false;
function queueMenuAutosave(){clearTimeout(autoSaveTimer);autoSaveTimer=setTimeout(saveMenuAutosave,900)}
async function saveMenuAutosave(){if(autoSaving)return;autoSaving=true;try{syncAllCards();[content,map]=await Promise.all([api("/api/admin/content",{method:"PUT",body:JSON.stringify(content)}),api("/api/admin/map",{method:"PUT",body:JSON.stringify(map)})]);const el=$("#mapping-state");if(el){el.textContent="Saved automatically";setTimeout(()=>{if(el.textContent==="Saved automatically")el.textContent=""},1600)}}catch(e){const el=$("#mapping-state");if(el)el.textContent=`Auto-save failed: ${e.message}`}finally{autoSaving=false}}
async function loadPersistenceStatus(){const el=$("#persistence-state");if(!el)return;try{const s=await api("/api/admin/persistence/status");el.innerHTML=s.persistent&&s.writable?`<span class="status available">PERSISTENT</span> Menu data is stored in ${esc(s.dataDir)}. Recovery copies: ${s.historyCount}.`:`<span class="status sold">VOLATILE</span> Menu data can be replaced by a restart or deployment. Attach a Render disk before relying on Menu Builder edits.`}catch(e){el.textContent=e.message}}

async function saveAll(){try{syncAllCards();settings.square.locationId=$("#location").value.trim();settings.theme.adobeFontsUrl=$("#adobe").value.trim();settings.theme.red=$("#red").value;settings.theme.navy=$("#navy").value;settings.theme.cream=$("#cream").value;settings.theme.aqua=$("#aqua").value;settings.display.weekendSurchargeOnlyOnWeekends=$("#weekend").checked;document.querySelectorAll(".promo-row").forEach(el=>{const p=content.promotions[Number(el.dataset.i)];p.name=el.querySelector(".pn").value;p.message=el.querySelector(".pm").value;p.start=el.querySelector(".ps").value;p.end=el.querySelector(".pe").value;p.enabled=el.querySelector(".pen").checked});[settings,content,map]=await Promise.all([api("/api/settings",{method:"PUT",body:JSON.stringify(settings)}),api("/api/admin/content",{method:"PUT",body:JSON.stringify(content)}),api("/api/admin/map",{method:"PUT",body:JSON.stringify(map)})]);$("#save-state").textContent="Saved and published successfully.";setTimeout(()=>$("#save-state").textContent="",3000);renderItems();await loadLiveStatus(true)}catch(e){$("#save-state").textContent=e.message;alert(e.message)}}
$("#save").onclick=saveAll;$("#save-items").onclick=saveAll;
async function loadLiveStatus(force=false){const checked=$("#live-checked"),body=$("#live-status-body");if(!body)return;try{const d=await api("/api/admin/live-status"+(force?"?refresh=1":""));checked.textContent=`Location ${d.locationId||"not set"} · checked ${new Date(d.checkedAt).toLocaleTimeString("en-AU")}`;body.innerHTML=d.rows.map(x=>{const status=x.soldOut?'<span class="status sold">SOLD OUT</span>':(x.active?'<span class="status available">AVAILABLE</span>':'<span class="status warning">UNAVAILABLE</span>');return `<tr><td><strong>${esc(x.menuName)}</strong><small>${esc(sectionLabels[x.section]||x.section)}</small></td><td>${esc(x.itemName||"Unknown")} — ${esc(x.variationName||"")}<small>${esc(x.squareVariationId)}</small></td><td>${status}</td></tr>`}).join("")||'<tr><td colspan="3">No mapped Square variations.</td></tr>'}catch(e){checked.textContent=e.message;body.innerHTML='<tr><td colspan="3">Unable to retrieve live Square status.</td></tr>'}}
$("#refresh-live").onclick=()=>loadLiveStatus(true);setInterval(()=>{if(!$("#app").hidden)loadLiveStatus(false)},10000);
async function loadMappingAudit(force=false){const box=$("#mapping-summary");if(!box)return;try{const d=await api("/api/admin/mapping-audit"+(force?"?refresh=1":"")),counts=d.rows.reduce((a,x)=>(a[x.status]=(a[x.status]||0)+1,a),{});box.innerHTML=`<span class="map-pill good">${counts.mapped||0} manually mapped</span><span class="map-pill auto">${counts["auto-matched"]||0} auto-matched</span><span class="map-pill bad">${counts.unmapped||0} unmapped</span>`;document.querySelectorAll(".item").forEach(el=>{const row=d.rows.find(x=>x.menuId===el.dataset.id);if(!row)return;let badge=el.querySelector(".map-state");if(!badge){badge=document.createElement("div");badge.className="map-state";el.prepend(badge)}badge.className=`map-state ${row.status}`;badge.textContent=row.status==="mapped"?"MAPPED":row.status==="auto-matched"?`AUTO: ${row.matches.map(m=>m.itemName+(m.variationName?` — ${m.variationName}`:"")).join(", ")}`:"UNMAPPED"})}catch(e){box.textContent=e.message}}
$("#auto-map").onclick=async()=>{syncAllCards();const state=$("#mapping-state");state.textContent="Matching menu rows to Square…";try{await api("/api/admin/map",{method:"PUT",body:JSON.stringify(map)});const d=await api("/api/admin/auto-map",{method:"POST",body:"{}"});map=d.map;renderItems();await loadLiveStatus(true);state.textContent=`Mapped ${d.mapped} rows. ${d.unmapped} rows still need manual review.`}catch(e){state.textContent=e.message}};
begin();

function formatBytes(value){const n=Number(value||0);if(!n)return "—";if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`}
async function loadBackups(){const state=$("#drive-state"),body=$("#backup-list-body"),connect=$("#connect-drive"),disconnect=$("#disconnect-drive");if(!state||!body)return;state.textContent="Checking Google Drive…";try{const s=await api("/api/admin/backups/status");connect.hidden=s.connected;disconnect.hidden=!s.connected;state.innerHTML=s.connected?`<span class="status available">CONNECTED</span> Google Drive is ready.${s.storagePersistent?"":" <strong>Warning:</strong> OAuth connection is not on persistent storage."}`:s.configured?`<span class="status warning">NOT CONNECTED</span> Click Connect Google Drive.${s.error?` ${esc(s.error)}`:""}`:'<span class="status sold">SETUP REQUIRED</span> Add the Google OAuth environment variables in Render.';$("#last-backup").textContent=s.lastBackup?new Date(s.lastBackup.createdTime).toLocaleString("en-AU"):"No backup yet";$("#next-backup").textContent=s.nextScheduled||"3:00 am Australia/Sydney";$("#backup-count").textContent=String(s.count||0);let files=[];if(s.connected){const l=await api("/api/admin/backups");files=l.files||[]}body.innerHTML=files.map(f=>`<tr><td>${new Date(f.createdTime).toLocaleString("en-AU")}</td><td><strong>${esc(f.name)}</strong><small>${esc(f.id)}</small></td><td>${formatBytes(f.size)}</td><td><button class="restore-backup danger" data-id="${esc(f.id)}" data-name="${esc(f.name)}">Restore</button>${f.webViewLink?` <a class="backup" href="${esc(f.webViewLink)}" target="_blank" rel="noopener">Open Drive</a>`:""}</td></tr>`).join("")||`<tr><td colspan="4">${s.connected?"No Google Drive backups found.":"Connect Google Drive to begin automatic backups."}</td></tr>`;document.querySelectorAll(".restore-backup").forEach(b=>b.onclick=()=>restoreBackup(b.dataset.id,b.dataset.name))}catch(e){state.textContent=e.message;body.innerHTML=`<tr><td colspan="4">${esc(e.message)}</td></tr>`}}
async function runBackupNow(){const out=$("#backup-action-state");out.textContent="Creating and verifying backup…";try{const d=await api("/api/admin/backups/run",{method:"POST",body:"{}"});out.textContent=`Backup complete: ${d.file.name}`;await loadBackups()}catch(e){out.textContent=e.message}}
async function restoreBackup(fileId,name){if(!confirm(`Restore ${name}? A safety backup of the current menu will be created first.`))return;const out=$("#backup-action-state");out.textContent="Creating safety backup and restoring…";try{await api("/api/admin/backups/restore",{method:"POST",body:JSON.stringify({fileId})});out.textContent="Restore completed. Reloading menu data…";[settings,content,map]=await Promise.all([api("/api/settings"),api("/api/admin/content"),api("/api/admin/map")]);fill();renderPromos();renderItems();await loadBackups();await loadLiveStatus(true)}catch(e){out.textContent=e.message}}
async function connectGoogleDrive(){try{const d=await api("/api/admin/google/connect");const popup=window.open(d.url,"bhfc-google-drive","width=620,height=760");if(!popup)throw Error("Allow pop-ups for this site, then try again.");const timer=setInterval(async()=>{if(popup.closed){clearInterval(timer);await loadBackups()}},700)}catch(e){$("#backup-action-state").textContent=e.message}}
async function disconnectGoogleDrive(){if(!confirm("Disconnect Google Drive backups? Existing backup files in Drive will not be deleted."))return;try{await api("/api/admin/google/disconnect",{method:"POST",body:"{}"});await loadBackups()}catch(e){$("#backup-action-state").textContent=e.message}}
if($("#backup-now"))$("#backup-now").onclick=runBackupNow;if($("#refresh-backups"))$("#refresh-backups").onclick=loadBackups;if($("#connect-drive"))$("#connect-drive").onclick=connectGoogleDrive;if($("#disconnect-drive"))$("#disconnect-drive").onclick=disconnectGoogleDrive;

if($("#restore-local"))$("#restore-local").onchange=async e=>{const file=e.target.files?.[0];if(!file)return;if(!confirm("Restore this local backup? Current menu data will be replaced."))return;try{const payload=JSON.parse(await file.text());await api("/api/admin/restore-local",{method:"POST",body:JSON.stringify(payload)});[settings,content,map]=await Promise.all([api("/api/settings"),api("/api/admin/content"),api("/api/admin/map")]);fill();renderPromos();renderItems();alert("Backup restored successfully.")}catch(err){alert(err.message)}finally{e.target.value=""}};


function fitPreview(){const frame=document.querySelector(".preview-frame"),iframe=frame?.querySelector("iframe");if(!frame||!iframe)return;frame.style.setProperty("--preview-scale",String(Math.min(frame.clientWidth/1920,frame.clientHeight/1080)))}
addEventListener("resize",fitPreview,{passive:true});
function formatLocalBytes(n){if(!n)return"0 B";const u=["B","KB","MB"],i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),2);return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`}
async function loadSystemHealth(){try{const s=await api("/api/admin/system-health");const el=$("#mapping-health");if(el)el.innerHTML=s.mapping.status==="healthy"?`<span class="status available">HEALTHY</span> ${s.mapping.mapped}/${s.mapping.total} menu rows mapped.`:`<span class="status warning">ATTENTION</span> ${s.mapping.mapped}/${s.mapping.total} mapped; ${s.mapping.unmapped} unmapped; ${s.mapping.duplicates.length} duplicate mapping(s).`;const b=$("#local-backup-state");if(b)b.innerHTML=s.persistent?`<span class="status available">PERSISTENT</span> ${s.backups.count} backups stored in ${esc(s.dataDir)}.`:`<span class="status sold">VOLATILE</span> DATA_DIR is ${esc(s.dataDir)}.`}catch(e){console.warn(e)}}
async function loadLocalBackups(){const body=$("#local-backup-list");if(!body)return;try{const d=await api("/api/admin/local-backups");body.innerHTML=(d.files||[]).map(f=>`<tr><td>${new Date(f.modifiedAt).toLocaleString("en-AU")}</td><td><strong>${esc(f.name)}</strong></td><td>${formatLocalBytes(f.size)}</td><td><a class="backup" href="/api/admin/local-backups/${encodeURIComponent(f.name)}/download">Download</a> <button class="restore-local-file danger" data-name="${esc(f.name)}">Restore</button></td></tr>`).join("")||'<tr><td colspan="4">No local backups yet.</td></tr>';document.querySelectorAll(".restore-local-file").forEach(b=>b.onclick=async()=>{if(!confirm(`Restore ${b.dataset.name}? A safety backup will be created first.`))return;await api(`/api/admin/local-backups/${encodeURIComponent(b.dataset.name)}/restore`,{method:"POST",body:"{}"});location.reload()})}catch(e){body.innerHTML=`<tr><td colspan="4">${esc(e.message)}</td></tr>`}}
async function runLocalBackup(){const out=$("#local-backup-message");if(out)out.textContent="Creating backup…";try{const d=await api("/api/admin/local-backups/run",{method:"POST",body:JSON.stringify({reason:"manual"})});if(out)out.textContent=`Created ${d.filename}`;await Promise.all([loadLocalBackups(),loadSystemHealth()])}catch(e){if(out)out.textContent=e.message}}
if($("#local-backup-now"))$("#local-backup-now").onclick=runLocalBackup;if($("#refresh-local-backups"))$("#refresh-local-backups").onclick=loadLocalBackups;
