const ORDER_URL = "https://www.brunswickheadsfishandchippery.com.au/order-online";
document.querySelectorAll("[data-order-link]").forEach(a=>a.href=ORDER_URL);
const header=document.querySelector(".site-header");
addEventListener("scroll",()=>header.classList.toggle("scrolled",scrollY>35),{passive:true});
const toggle=document.querySelector(".nav-toggle"),nav=document.querySelector("#site-nav");
if(toggle&&nav){toggle.addEventListener("click",()=>{const open=nav.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open))});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");toggle.setAttribute("aria-expanded","false")}));}
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const preferredOrder=["Beer Battered Fish","Crumbed Fish","Grilled Fish","Burgers & Tacos","Packs","Snacks","Chips"];
function classifySection(section){const raw=String(section||"").trim(),c=raw.toLowerCase().replace(/[^a-z0-9]/g,"");if(c.includes("drink"))return null;if(c==="freshfish"||c.includes("beerbatter")||c==="fresh")return "Beer Battered Fish";if(c.includes("crumb"))return "Crumbed Fish";if(c.includes("grill")||c==="addchips")return "Grilled Fish";if(c.includes("burger")||c.includes("taco"))return "Burgers & Tacos";if(c.includes("pack")||c.includes("basket"))return "Packs";if(c.includes("snack"))return "Snacks";if(c.includes("chip"))return "Chips";return raw;}
let menuData=null,activeCategory="all";
function rowMarkup(item){const detail=item.detail?`<small>${esc(item.detail)}</small>`:"";const price=item.soldOut?"SOLD OUT":esc(item.priceText??item.price??"");return `<div class="web-menu-row ${item.soldOut?"sold-out":""}"><span class="label">${esc(item.name)}${item.origin?`<sup>${esc(item.origin)}</sup>`:""}${detail}</span><span class="dots"></span><span class="price">${price}</span></div>`;}
function groupedMenu(){const groups=new Map();Object.entries(menuData?.sections||{}).forEach(([section,items])=>{const label=classifySection(section);if(!label)return;if(!groups.has(label))groups.set(label,[]);groups.get(label).push(...items)});return preferredOrder.filter(n=>groups.has(n)).map(n=>[n,groups.get(n)]);}
function sectionBody(name,items){if(name!=="Burgers & Tacos")return items.map(rowMarkup).join("");let html="",dividerAdded=false;items.forEach(item=>{const isTaco=/taco/i.test(item.name||"");if(isTaco&&!dividerAdded){html+='<div class="menu-subheading">TACOS</div>';dividerAdded=true;}html+=rowMarkup(item)});return html;}
function renderMenu(){const ordered=groupedMenu(),tabs=document.querySelector("#menu-tabs");const names=["all",...ordered.map(([n])=>n)];tabs.innerHTML=names.map(n=>`<button type="button" class="${n===activeCategory?"active":""}" data-category="${esc(n)}">${n==="all"?"All Menu":esc(n)}</button>`).join("");tabs.querySelectorAll("button").forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;renderMenu()});document.querySelector("#web-menu").innerHTML=ordered.filter(([n])=>activeCategory==="all"||n===activeCategory).map(([n,items])=>`<article class="menu-card"><h3>${esc(n)}</h3>${sectionBody(n,items)}</article>`).join("")||'<div class="loading">No menu items available.</div>';}
async function loadMenu(){try{const r=await fetch("/api/live-menu",{cache:"no-store"});if(!r.ok)throw Error();menuData=await r.json();renderMenu()}catch{document.querySelector("#web-menu").innerHTML='<div class="loading">Use Order Online to view the current ordering menu.</div>'}}
function fmt(v){if(!v)return"";const d=new Date(v);return Number.isNaN(d.getTime())?"":d.toLocaleTimeString("en-AU",{hour:"numeric",minute:"2-digit"})}
async function loadGoogle(){try{const p=await(await fetch("/api/google-place",{cache:"no-store"})).json();if(p.formattedAddress)document.querySelector("#google-address").innerHTML=esc(p.formattedAddress).replace(", Brunswick Heads","<br>Brunswick Heads");const s=document.querySelector("#open-status"),t=document.querySelector("#today-hours");s.textContent=p.openNow===true?"Open now":p.openNow===false?"Closed now":"Open daily";const c=fmt(p.nextCloseTime),o=fmt(p.nextOpenTime);t.textContent=p.openNow===true&&c?`Closes at ${c}`:p.openNow===false&&o?`Opens at ${o}`:"11:30am–7:00pm";document.querySelector("#weekly-hours-list").innerHTML=(p.weekdayDescriptions||[]).map(x=>`<span>${esc(x)}</span>`).join("");const rating=document.querySelector("#google-rating");if(p.rating){rating.hidden=false;rating.textContent=`★ ${Number(p.rating).toFixed(1)}${p.userRatingCount?` · ${Number(p.userRatingCount).toLocaleString("en-AU")} Google reviews`:""}`}if(p.googleMapsUri)document.querySelector("#google-directions").href=p.googleMapsUri}catch{}try{const c=await(await fetch("/api/google-map-config")).json();if(c.configured)document.querySelector("#google-map").src=`https://www.google.com/maps/embed/v1/place?key=${encodeURIComponent(c.embedKey)}&q=place_id:${encodeURIComponent(c.placeId)}`}catch{}}
loadMenu();loadGoogle();setInterval(loadMenu,30000);
