const ORDER_URL="https://www.brunswickheadsfishandchippery.com.au/order-online";
document.querySelectorAll("[data-order-link]").forEach(a=>a.href=ORDER_URL);
const header=document.querySelector(".site-header");addEventListener("scroll",()=>header.classList.toggle("scrolled",scrollY>35),{passive:true});
const toggle=document.querySelector(".nav-toggle"),nav=document.querySelector("#site-nav");toggle.addEventListener("click",()=>{const o=nav.classList.toggle("open");toggle.setAttribute("aria-expanded",String(o))});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");toggle.setAttribute("aria-expanded","false")}));
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function row(item){const detail=item.detail?`<small>${esc(item.detail)}</small>`:"";return `<div class="web-menu-row ${item.soldOut?"sold-out":""}"><span class="label">${esc(item.name)}${item.origin?`<sup>${esc(item.origin)}</sup>`:""}${detail}</span><span class="dots"></span><span class="price">${item.soldOut?"SOLD OUT":esc(item.priceText??item.price??"")}</span></div>`}
function section(title,items,extraClass=""){if(!items?.length)return"";return `<section class="menu-card ${extraClass}"><h3>${title}</h3>${items.map(row).join("")}</section>`}
function takeFishermans(data){const found=[];for(const key of Object.keys(data)){data[key]=(data[key]||[]).filter(i=>{if(/fisherman'?s basket/i.test(i.name||"")){found.push(i);return false}return true})}return found}
function renderMenu(data){
  const s=structuredClone(data.sections||{});
  const packs=[...(s.packs||[]),...takeFishermans(s)];
  const left=section("BEER BATTERED FISH",s.freshFish)+section("CRUMBED FISH",s.crumbed)+section("GRILLED FISH",s.grilled)+section("ADD CHIPS",s.addChips,"compact");
  const middle=section("BURGERS",s.burgers)+section("TACOS",s.tacos);
  const right=section("PACKS",packs)+section("SNACKS",s.snacks)+section("CHIPS",s.chips);
  document.querySelector("#web-menu").innerHTML=`<div class="menu-column">${left}</div><div class="menu-column">${middle}</div><div class="menu-column">${right}</div>`;
}
async function loadMenu(){try{const r=await fetch("/api/live-menu",{cache:"no-store"});if(!r.ok)throw Error();renderMenu(await r.json())}catch{document.querySelector("#web-menu").innerHTML='<div class="loading">Use Order Online to view the current menu.</div>'}}
function fmt(v){if(!v)return"";const d=new Date(v);return Number.isNaN(d.getTime())?"":d.toLocaleTimeString("en-AU",{hour:"numeric",minute:"2-digit"})}
async function loadGoogle(){try{const p=await(await fetch("/api/google-place",{cache:"no-store"})).json();if(p.formattedAddress)document.querySelector("#google-address").innerHTML=esc(p.formattedAddress).replace(", Brunswick Heads","<br>Brunswick Heads").replace(", Australia","");if(p.rating){const e=document.querySelector("#google-rating");e.hidden=false;e.textContent=`★ ${Number(p.rating).toFixed(1)}${p.userRatingCount?` · ${Number(p.userRatingCount).toLocaleString("en-AU")} Google reviews`:""}`}const st=document.querySelector("#open-status"),th=document.querySelector("#today-hours");st.textContent=p.openNow===true?"Open now":p.openNow===false?"Closed now":"Open daily";th.textContent=p.openNow===true&&p.nextCloseTime?`Closes at ${fmt(p.nextCloseTime)}`:p.openNow===false&&p.nextOpenTime?`Opens at ${fmt(p.nextOpenTime)}`:"11:30am–7:00pm";document.querySelector("#weekly-hours-list").innerHTML=(p.weekdayDescriptions||[]).map(x=>`<span>${esc(x)}</span>`).join("");if(p.googleMapsUri)document.querySelector("#google-directions").href=p.googleMapsUri}catch{}
try{const c=await(await fetch("/api/google-map-config")).json();const map=document.querySelector("#google-map");map.src=c.configured?`https://www.google.com/maps/embed/v1/place?key=${encodeURIComponent(c.embedKey)}&q=place_id:${encodeURIComponent(c.placeId)}`:"https://www.google.com/maps?q=Brunswick+Heads+Fish+and+Chippery&output=embed"}catch{}}
loadMenu();loadGoogle();setInterval(loadMenu,30000);