const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const money=v=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",minimumFractionDigits:Number.isInteger(v)?0:2,maximumFractionDigits:2}).format(v).replace("$","");
function row(x,cls=""){const rawDetail=String(x.detail||"").trim();const inlineWild=/^wild\s+caught$/i.test(rawDetail);const origin=x.origin?`<span class="origin">${esc(x.origin)}</span>`:"";const inlineDetail=inlineWild?`<span class="inline-detail">${esc(rawDetail)}</span>`:"";const detail=rawDetail&&!inlineWild?`<small class="detail">${esc(rawDetail)}</small>`:"";const price=x.soldOut?"SOLD OUT":(x.noPrice?"":(x.priceText||money(Number(x.price||0))));return `<div class="menu-row ${cls} ${x.soldOut?"sold-out":""}"><span class="copy"><span class="item-line"><strong>${esc(x.name)}</strong>${origin}${inlineDetail}</span>${detail}</span><span class="leader"></span><span class="price">${esc(price)}</span></div>`}
function isKidsPack(x){return /(?:kids?|little\s+deckhands?)/i.test(`${x.name||""} ${x.detail||""}`)}
function apply(s){const r=document.documentElement.style;r.setProperty("--cream",s.theme.cream);r.setProperty("--navy",s.theme.navy);r.setProperty("--red",s.theme.red);r.setProperty("--aqua",s.theme.aqua);r.setProperty("--heading-font",s.theme.headingFont);r.setProperty("--body-font",s.theme.bodyFont);document.querySelector("#footer-left").textContent=`◎  ${s.business.instagram}`;document.querySelector("#footer-centre").textContent=s.business.footerCentre;document.querySelector("#footer-right").textContent=s.business.footerRight;if(s.theme.adobeFontsUrl&&!document.querySelector("#adobe-fonts")){const l=document.createElement("link");l.id="adobe-fonts";l.rel="stylesheet";l.href=s.theme.adobeFontsUrl;document.head.appendChild(l)}}
async function load(){try{const r=await fetch("/api/live-menu",{cache:"no-store"});const d=await r.json();apply(d.settings);for(const k of ["freshFish","crumbed","grilled","addChips","burgers","tacos"]){const host=document.querySelector(`[data-section="${k}"]`);if(host)host.innerHTML=(d.sections[k]||[]).map(x=>row(x)).join("")}
const packs=d.sections.packs||[], kids=packs.filter(isKidsPack), regular=packs.filter(x=>!isKidsPack(x));document.querySelector('[data-section="packs-main"]').innerHTML=regular.map(x=>row(x,"pack-row")).join("");document.querySelector('[data-section="packs-kids"]').innerHTML=kids.map(x=>row(x,"kid-pack-row")).join("");document.querySelector('#deckhands').hidden=!kids.length;
document.body.classList.toggle("offline",!d.squareOnline)}catch{document.body.classList.add("offline")}}
load();setInterval(load,10000);
