services:
  - type: web
    name: bhfc-website-stage1
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MENU_API_URL
        value: https://bhfc-digital-menu.onrender.com/api/menu
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: GOOGLE_PLACE_ID
        sync: false
      - key: GOOGLE_MAPS_EMBED_API_KEY
        sync: false
